#!/bin/bash

# VISUAL STARTUP GUIDE
# Run this file to get a guided walk-through

echo ""
echo "╔═══════════════════════════════════════════════════════════════════════╗"
echo "║          🚀 Legal Drafting Assistant - Startup Guide 🚀             ║"
echo "╚═══════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📍 LOCATION: /Users/apurboshib/Desktop/Apurbo/Project_02"
echo ""

echo "📋 STEP 1: Get Your Anthropic API Key"
echo "   ├─ Go to: https://console.anthropic.com"
echo "   ├─ Create account or login"
echo "   ├─ Copy your API key (starts with 'sk-ant-')"
echo "   └─ Keep it safe!"
echo ""

echo "✏️  STEP 2: Configure Environment"
echo "   $ nano .env"
echo ""
echo "   Add this line:"
echo "   ANTHROPIC_API_KEY=sk-ant-your-key-here"
echo ""
echo "   Save: Ctrl+X, then Y, then Enter"
echo ""

echo "🔧 STEP 3: Choose Your Launch Method"
echo ""
echo "   Option A (RECOMMENDED): Auto-setup"
echo "   ├─ Run: ./run.sh"
echo "   ├─ This will:"
echo "   │  ├─ Create virtual environment"
echo "   │  ├─ Install dependencies"
echo "   │  ├─ Start server"
echo "   │  └─ Open browser to http://localhost:8000"
echo "   └─ Perfect for first-time setup"
echo ""

echo "   Option B: Manual setup"
echo "   ├─ Run: python3 -m venv .venv"
echo "   ├─ Run: source .venv/bin/activate"
echo "   ├─ Run: pip install -r requirements.txt"
echo "   ├─ Run: uvicorn app.main:app --reload"
echo "   └─ Then open http://localhost:8000"
echo ""

echo "   Option C: Production server"
echo "   ├─ Run: ./run-api.sh"
echo "   ├─ This will:"
echo "   │  └─ Start with 2 workers (more stable)"
echo "   └─ Then open http://localhost:8000"
echo ""

echo "🌐 STEP 4: Use the Application"
echo "   ├─ Browser opens to http://localhost:8000"
echo "   ├─ Upload a PDF or text document"
echo "   ├─ Select a draft type (memo, notice, etc.)"
echo "   ├─ Click 'Generate Draft'"
echo "   ├─ Review the AI-generated draft with citations"
echo "   ├─ Edit the draft to train the system"
echo "   └─ Save edits → system learns your preferences"
echo ""

echo "📁 Sample Workflow"
echo "   $ ./run.sh"
echo "   # Browser opens"
echo "   # 1. Upload: samples/sample_notice.txt"
echo "   # 2. Select: Notice-Related Summary"
echo "   # 3. Generate: Click button"
echo "   # 4. Review: Read the draft + evidence"
echo "   # 5. Edit: Make improvements"
echo "   # 6. Save: System learns!"
echo ""

echo "📚 API Examples"
echo "   # Process document"
echo "   $ curl -X POST -F 'file=@samples/sample_notice.txt' http://localhost:8000/api/process"
echo ""
echo "   # Generate draft"
echo "   $ curl -X POST http://localhost:8000/api/draft \\"
echo "       -H 'Content-Type: application/json' \\"
echo "       -d '{\"doc_ids\":[\"<id>\"],\"draft_type\":\"notice_summary\"}'"
echo ""
echo "   # View results"
echo "   $ curl http://localhost:8000/api/documents"
echo "   $ curl http://localhost:8000/api/drafts"
echo "   $ curl http://localhost:8000/api/rules"
echo ""

echo "🛑 Stopping the Server"
echo "   Press: Ctrl+C in the terminal"
echo ""

echo "📖 Documentation"
echo "   ├─ README.md             → Full guide"
echo "   ├─ QUICKSTART.md         → Quick setup"
echo "   ├─ PROJECT_COMPLETION.md → What's implemented"
echo "   └─ This file             → You're reading it!"
echo ""

echo "🐛 Troubleshooting"
echo "   ├─ Port 8000 in use?"
echo "   │  └─ Change port: uvicorn app.main:app --port 8001"
echo "   ├─ Module not found?"
echo "   │  └─ Make sure virtual env is activated"
echo "   ├─ API key not working?"
echo "   │  └─ Check .env file has your key"
echo "   └─ Database error?"
echo "      └─ rm data/app.db && ./run.sh"
echo ""

echo "✨ You're all set!"
echo ""
echo "Next: Run → ./run.sh"
echo ""
